// Shared in-memory store for roadmaps across all routes
// This ensures roadmaps generated by n8n are accessible via the roadmap GET endpoint

let roadmaps = [];
let users = [];

export const getRoadmaps = () => roadmaps;
export const setRoadmaps = (newRoadmaps) => { roadmaps = newRoadmaps; };
export const addRoadmap = (roadmap) => { roadmaps.push(roadmap); return roadmap; };
export const getRoadmapsByUserId = (userId) => roadmaps.filter(r => r.userId === userId);
export const getRoadmapById = (id) => roadmaps.find(r => r.id === id);
export const deleteRoadmapById = (id) => { roadmaps = roadmaps.filter(r => r.id !== id); };

export const getUsers = () => users;
export const setUsers = (newUsers) => { users = newUsers; };
export const addUser = (user) => { users.push(user); return user; };
